DjangoAdmin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import PermissionDenied, LoginRequired

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('accounts.urls')),
    path('residence/', include('residence.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('guide/', include('guide.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('search.urls')),
    path('permission_denied/', PermissionDenied.as_view(),
         name='permission denied'),
    path('login_required/', LoginRequired.as_view()),

]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include

urlpatterns = [
    path('', views.blog, name='blog'),
    # path('', views.new_post.as_view(), name='newpost'),
    path('newpost/', views.new_post, name='newpost'),
    # url(r'^newpost(?P<pk>[0-9]+)/$', views.new_post, name='newpost'),
    path('bloglist/', views.PostList, name='bloglist'),
    # path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    # path('<int:id>/', views.PostDetail, name='post_detail'),
    # path()
    
    url(r'^bloglist/(?P<pk>[0-9]+)/$',
        views.PostDetail.as_view(), name='post_detail'),
    url(r'^bloglist/(?P<postid>\d+)/preference/(?P<userpreference>\d+)/$',
        views.PostPreference, name='postpreference'),
    # url(r'^like/(?P<pk>[0-9]+)/$', views.like_post, name='like_post'),
    # path('like/', views.like_post, name='like_post'),
    url(r'^blogist/(?P<pk>[0-9]+)/edit/$',
        views.UpdatePost.as_view(), name='post_edit'),
    url(r'^bloglist/(?P<pk>[0-9]+)/remove/$',
        views.DeletePost.as_view(), name='post_remove'),



    url(r'^bloglist/(?P<pk>[0-9]+)/approve/$',
        views.comment_approve, name='comment_approve'),
    url(r'^bloglist/(?P<pk>[0-9]+)/remove/$',
        views.comment_remove, name='comment_remove'),

    url(r'^bloglist/(?P<pk>[0-9]+)/comment/$',
        views.addComment, name='addcomment'),


]

search/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('restaurant/', views.SearchRestaurant.as_view(), name='search restaurant'),
    path('space/', views.SearchSpace.as_view()),
    path("guide/", views.SearchGuide.as_view()),
    path('sbt/', include('search.search_by_time')),
    path('ajax/', include('search.ajax_handler')),
]

guide/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q, F
from homepage.models import City, UserDetail, Address, Country
from homepage.base import *

# Create your models here.


class Gender(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name
    

class Guide(models.Model):
    user_detail = models.ForeignKey(UserDetail, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=True, default=None)
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name="guide", null=True, default=None)
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="guide", null=True, default=None)
    mobile = models.IntegerField()
    img = models.ImageField(upload_to='GuidePhoto', default=None, null=True, blank=True)
    description = models.CharField(max_length=255, default=None, null=True, blank=True)
    rent = models.FloatField(null=True)
    
    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)
        if not (exclude and "user_detail" in exclude):
            if Guide.objects.filter(user_detail=self.user_detail, name=self.name).exists():
                if Guide.objects.get(user_detail=self.user_detail, name=self.name).id != self.id:
                    raise ValidationError("You have already a guide of the same name")
        if Guide.objects.filter(mobile=self.mobile).exists():
            if Guide.objects.get(mobile=self.mobile).id != self.id:
                raise ValidationError("This mobile number is already used")
            
    def __str__(self):
        return self.name


class GuideAvailable(models.Model):
    guide = models.ForeignKey(Guide, on_delete=models.CASCADE)
    avail_from = models.DateField()
    avail_to = models.DateField()

    def __str__(self):
        return '%s %s %s' % (self.guide.__str__(), str(self.avail_from), str(self.avail_to))


class GuideBooking(models.Model):
    guide = models.ForeignKey(Guide, on_delete=models.CASCADE)
    customer = models.ForeignKey(UserDetail, on_delete=models.CASCADE)
    book_from = models.DateField()
    book_to = models.DateField()
    total_rent = models.FloatField()
    booking_time = models.DateTimeField(null=True)

    def __str__(self):
        return '%s hired by %s from %s to %s' % (self.guide.__str__(), self.customer.__str__(), str(self.book_from),
                                                 str(self.book_to))


'''
class BookManager(models.Manager):
    def create_book(self, title):
        book = self.create(title=title)
        # do something with the book
        return book

class Book(models.Model):
    title = models.CharField(max_length=100)

    objects = BookManager()

book = Book.objects.create_book("Pride and Prejudice")
'''


# pip install Pillow
# python manage.py makemigrations
# python manage.py sqlmigrate @appname @migrationid
# python manage.py migrate
# django admin username-shoaib password-1234
# python manage.py createsuperuser @username
# python manage.py changepassword @username
# python manage.py createsuperuser -h

search/models.py
from homepage.base import *

# Create your models here.

search/forms.py
from django import forms
from homepage.models import MyChoice, Country, City
from homepage.base import *
from .first_view import load_city_choice, load_flw_from_day, load_flw_from_month, load_flw_to_day, load_flw_to_month, load_flw_to_year, load_residence_choice
from residence.models import Residence


class SearchRestaurantForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        country_choice = [("", "------------")]
        for ob in Country.objects.all():
            country_choice += [(ob.id, str(ob.name))]
        self.fields['country'] = forms.ChoiceField(choices=country_choice)
        self.fields['city'] = forms.ChoiceField(
            choices=[(o.id, str(o)) for o in City.objects.none()], required=False)

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'] = forms.ChoiceField(
                    choices=[(o.id, str(o)) for o in City.objects.filter(country_id=country_id)], required=False)

            except (ValueError, TypeError):
                pass


class SpaceSearchForm(forms.Form):
    space_n = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 100)], label="Number of Space")
    person_n = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 100)], label="Person per Room")
    max_rent = forms.CharField(label="Maximal Rent", required=False)
    min_rent = forms.CharField(label="Minimal Rent", required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        today = date.today()
        year_choice = [("", "------------")]
        for i in range(datetime.today().year, datetime.today().year+5):
            year_choice += [(i, str(i))]
        self.fields['from_year'] = forms.ChoiceField(
            choices=year_choice, label="From Year")
        self.fields['from_month'] = forms.ChoiceField(
            choices=[("", "------------")], label="From Month")
        self.fields['from_day'] = forms.ChoiceField(
            choices=[("", "------------")], label="From Day")
        self.fields['to_year'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Year')
        self.fields['to_month'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Month')
        self.fields['to_day'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Day')

        if 'from_year' in self.data:
            from_month = int(self.data['from_month'])
            from_year = int(self.data['from_year'])
            from_day = int(self.data['from_day'])
            to_day = int(self.data['to_day'])
            to_month = int(self.data['to_month'])
            to_year = int(self.data['to_year'])

            self.fields['from_month'] = forms.ChoiceField(
                choices=load_flw_from_month(from_year))
            self.fields['from_day'] = forms.ChoiceField(
                choices=load_flw_from_day(from_year, from_month))
            self.fields['to_year'] = forms.ChoiceField(
                choices=load_flw_to_year(from_year))
            self.fields['to_month'] = forms.ChoiceField(
                choices=load_flw_to_month(from_year, to_year, from_month))
            self.fields['to_day'] = forms.ChoiceField(choices=load_flw_to_day(
                from_year, to_year, from_month, to_month, from_day))

        country_choice = [("", "------------")]
        for ob in Country.objects.all():
            country_choice += [(ob.id, str(ob.name))]
        self.fields['country'] = forms.ChoiceField(choices=country_choice)

        self.fields['city'] = forms.ChoiceField(choices=[("", "------------")])
        if 'country' in self.data:
            country = int(self.data.get('country', None))
            self.fields['city'] = forms.ChoiceField(
                choices=load_city_choice(City, country))

        self.fields['residence'] = forms.ChoiceField(label="Residence", choices=[
            ("", "------------")], required=False)
        if 'city' in self.data:
            city = int(self.data['city'])
            self.fields['residence'] = forms.ChoiceField(
                label="Residence", choices=load_residence_choice(Residence, city), required=False)

        # print('init spacesearch     form')


class SearchGuideForm(forms.Form):
    max_rent = forms.CharField(label="Maximal Rent", required=False)
    min_rent = forms.CharField(label="Minimal Rent", required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["gender"] = forms.ChoiceField(
            choices=[(1, "Male"), (2, "female")])

        year_choice = [("", "------------")]
        for i in range(datetime.today().year, datetime.today().year+5):
            year_choice += [(i, str(i))]
        self.fields['from_year'] = forms.ChoiceField(
            choices=year_choice, label="From Year")
        self.fields['from_month'] = forms.ChoiceField(
            choices=[("", "------------")], label="From Month")
        self.fields['from_day'] = forms.ChoiceField(
            choices=[("", "------------")], label="From Day")
        self.fields['to_year'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Year')
        self.fields['to_month'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Month')
        self.fields['to_day'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Day')

        if 'from_year' in self.data:
            from_month = int(self.data['from_month'])
            from_year = int(self.data['from_year'])
            from_day = int(self.data['from_day'])
            to_day = int(self.data['to_day'])
            to_month = int(self.data['to_month'])
            to_year = int(self.data['to_year'])

            self.fields['from_month'] = forms.ChoiceField(
                choices=load_flw_from_month(from_year))
            self.fields['from_day'] = forms.ChoiceField(
                choices=load_flw_from_day(from_year, from_month))
            self.fields['to_year'] = forms.ChoiceField(
                choices=load_flw_to_year(from_year))
            self.fields['to_month'] = forms.ChoiceField(
                choices=load_flw_to_month(from_year, to_year, from_month))
            self.fields['to_day'] = forms.ChoiceField(choices=load_flw_to_day(
                from_year, to_year, from_month, to_month, from_day))

        country_choice = [("", "------------")]
        for ob in Country.objects.all():
            country_choice += [(ob.id, str(ob.name))]
        self.fields['country'] = forms.ChoiceField(choices=country_choice)

        self.fields['city'] = forms.ChoiceField(choices=[("", "------------")])
        if 'country' in self.data:
            country = int(self.data.get('country', None))
            self.fields['city'] = forms.ChoiceField(
                choices=load_city_choice(City, country))

search/templates/ajax_city.html
{% for m,n in cities %}
<option value="{{m}}">{{n}}</option>
{% endfor %}

search/templates/jquery_test.html
<html>

<head>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>

<body>
    <div id="test">hi</div>
    <button id="b1">Click Me</button>

    <script>
        $("#b1").click(function () { $("#test").show(); });
        $("#b1").dblclick(function () { $("#test").hide(); });
    </script>
</body>

</html>

search/templates/load_city_residence.html
{% for m,n in qs %}
<option value="{{m}}">{{n}}</option>
{% endfor %}

search/templates/load_from_day.html
{% for m,n in day_arr %}
<option value="{{m}}">{{n}}</option>

{% endfor %}

search/templates/load_from_month.html
{% for m,n in month %}
<option value="{{m}}">{{n}}</option>
{% endfor %}

search/templates/load_to_day.html
{% for m,n in days %}
<option value="{{m}}">{{n}}</option>
{% endfor %}

search/templates/response.html
{{response}}

search/templates/search_guide.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content_1 %}
<title></title>
{% endblock content_1 %}

{% block header %}
{% endblock %}

{% block content_2 %}

<br> <br>
<div class="container">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            <div class="card searchbox" style="height: max-content;">
                <h3 class="card-header" style="background: #232524; color: #FFFF;">Search
                    Guide</h3>
                <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                <div class="card-body">

                    <form method="POST">
                        {% csrf_token %}
                        <!-- <table class="form_table"> -->
                        {{ form|crispy }}
                        <!-- </table> -->
                        <br>
                        <div class="text-right">
                            <button type="submit" style="font-family: Ubuntu;"
                                class="btn btn-dark btn-lg">Search</button>

                        </div>
                    </form>

                </div>
            </div>

        </div>
        <div class="col-lg-2">

        </div>


    </div>

</div> <br> <br>
<div class="container">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            {% if avails.exists %}
            <div class="card searchbox">
                <h3 class="card-header" style="background: #232524; color: #FFFF;">Results</h3>
                <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                {% for avail in avails %}
                <div class="card-body">
                    <div class="text-center">
                        <a href="/guide/{{avail.guide.id}}/">
                            <button class="btn btn-secondary btn-lg btn-block">{{avail.guide.name}}</button>
                        </a> <br>
                        {% if request.user.is_authenticated %}
                        <button class="book btn btn-info" guide="{{avail.guide.id}}">Book</button> <br>
                        {% endif %}

                    </div>

                </div>
                {% endfor %}
                {% else %}
                <div class="card-body">
                    <div class="text-center">
                        <button class="btn btn-dark">No Guides Found!</button>

                    </div>

                </div>
                {% endif %}
            </div>

        </div>
        <div class="col-lg-2">

        </div>


    </div>

</div>
<br> <br>





<script id="date_ajax" load_to_year="/search/ajax/load_to_year/" load_to_month="/search/ajax/load_to_month/"
    load_to_day="/search/ajax/load_to_day/" load_from_month="/search/ajax/load_from_month/"
    load_from_day="/search/ajax/load_from_day/">

        $("#id_from_year").change(function () {
            var year = $(this).val();
            var url = $("#date_ajax").attr("load_from_month");

            $.ajax({
                url: url,
                data: { 'year': year },
                success: function (shoaib) { $("#id_from_month").html(shoaib); }
            });

            $.ajax({
                url: $("#date_ajax").attr("load_to_year"),
                data: { 'year': year },
                success: function (redata) { $("#id_to_year").html(redata) }
            });
        });

        $("#id_from_month").change(function () {
            var year = $("#id_from_year").val();
            var month = $("#id_from_month").val();
            var url = $("#date_ajax").attr("load_from_day");

            $.ajax({
                url: url,
                data: { 'year': year, 'month': month },
                success: function (tasrif) { $("#id_from_day").html(tasrif); }
            });

            $.ajax({
                url: $("#date_ajax").attr("load_to_month"),
                data: { 'from_year': $("#id_from_year").val(), 'to_year': $("#id_to_year").val(), 'from_month': $("#id_from_month").val() },
                success: function (redata) { $("#id_to_month").html(redata); }
            });
        });

        $("#id_to_year").change(function () {
            $.ajax({
                url: $("#date_ajax").attr("load_to_month"),
                data: { 'from_year': $("#id_from_year").val(), 'to_year': $("#id_to_year").val(), 'from_month': $("#id_from_month").val() },
                success: function (redata) { $("#id_to_month").html(redata); }
            });
        });

        $("#id_to_month").change(function () {
            $.ajax({
                url: $("#date_ajax").attr("load_to_day"),
                data: {
                    'from_year': $("#id_from_year").val(),
                    'from_month': $("#id_from_month").val(),
                    'from_day': $("#id_from_day").val(),
                    'to_year': $("#id_to_year").val(),
                    'to_month': $("#id_to_month").val(),
                    "space_type": $(this).attr("")
                },
                success: function (redata) { $("#id_to_day").html(redata); }
            });
        });

        $("#id_from_day").change(function () {
            $.ajax({
                url: $("#date_ajax").attr("load_to_day"),
                data: {
                    'from_year': $("#id_from_year").val(),
                    'from_month': $("#id_from_month").val(),
                    'from_day': $("#id_from_day").val(),
                    'to_year': $("#id_to_year").val(),
                    'to_month': $("#id_to_month").val(),
                },
                success: function (redata) { $("#id_to_day").html(redata); }
            });
        });
    </script>

<script id="load_city_ajax" load_city="/search/ajax/load_city/" load_residence="/search/ajax/load_city_residence/">

    $("#id_country").change(function () {
        $.ajax({
            url: $("#load_city_ajax").attr("load_city"),
            data: { 'country': $("#id_country").val() },
            success: function (redata) {
                $("#id_city").html(redata);
            }
        });
    });

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $(".book").click(function () {
        $.ajax({
            url: "/guide/book/",
            type: "POST",
            data: {
                "from_year": $("#id_from_year").val(),
                "from_month": $("#id_from_month").val(),
                "from_day": $("#id_from_day").val(),
                "to_year": $("#id_to_year").val(),
                "to_month": $("#id_to_month").val(),
                "to_day": $("#id_to_day").val(),
                "guide": $(this).attr("guide")
            },
            success: function (response) {
                alert(response);
                $(".book").hide();
            }
        });
    });
</script>

{% endblock %}

search/templates/search_space.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content_1 %}
<title></title>
{% endblock content_1 %}

{% block header %}
{% endblock %}

{% block content_2 %}

<br> <br>
<div class="container">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            <div class="card searchbox" style="height: max-content;">
                <h3 class="card-header" style="background: #232524; color: #FFFF;">Search
                    Hotels/Residences</h3>
                <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                <div class="card-body">

                    <form method="POST">
                        {% csrf_token %}
                        <!-- <table class="form_table"> -->
                        {{ form|crispy }}
                        <!-- </table> -->
                        <br>
                        <div class="text-right">
                            <button type="submit" style="font-family: Ubuntu;"
                                class="btn btn-dark btn-lg">Search</button>

                        </div>
                    </form>

                </div>
            </div>

        </div>
        <div class="col-lg-2">

        </div>


    </div>

</div>
<br> <br>

<br> <br>
<div class="container">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            {% if restaurants.exists %}
            <div class="card searchbox">
                <h3 class="card-header" style="background: #232524; color: #FFFF;">Results</h3>
                <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                <table>
                    <tr>
                        <th><button class="btn btn-dark">Residence </button></th>
                        <th><button class="btn btn-dark">Space Type </button></th>
                        <th><button class="btn btn-dark">Details </button></th>
                    </tr>
                    {% for res in residence_qs %}
                    {% for ri,pk,name,count,rent in space_types_ri_p_n_c_r %}
                    {% if ri == res.id %}
                    <tr>
                        <td><a href="/residence/{{res.id}}/"><button
                                    class="body_table_data_button">{{res.name}}</button></a></td>
                        <td><a href="/residence/space_type/{{pk}}/"><button
                                    class="body_table_data_button">{{name}}</button></a></td>
                        <td>{{count}} Space Available at ${{rent}} per space</td>
                        {% if request.user.is_authenticated %}
                        <td><button class="book btn btn-dark" space_type="{{pk}}"
                                id="space_type_id_{{pk}}">Book</button>
                        </td>
                        {% endif %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                    {% endfor %}
                    {% else %}
                    <div class="card-body">
                        <div class="text-center">
                            <button class="btn btn-dark">No Hotels/Spaces Found!</button>

                        </div>

                    </div>
                    {% endif %}
                </table>
            </div>

        </div>
        <div class="col-lg-2">

        </div>


    </div>

</div>
<br> <br>


<script id="date_ajax" load_to_year="/search/ajax/load_to_year/" load_to_month="/search/ajax/load_to_month/"
    load_to_day="/search/ajax/load_to_day/" load_from_month="/search/ajax/load_from_month/"
    load_from_day="/search/ajax/load_from_day/">

        $("#id_from_year").change(function () {
            // $("#test").html('changed');
            var year = $(this).val();
            var url = $("#date_ajax").attr("load_from_month");
            // $("#test").html(url);

            $.ajax({
                url: url,
                data: { 'year': year },
                success: function (shoaib) { $("#id_from_month").html(shoaib); }
            });

            $.ajax({
                url: $("#date_ajax").attr("load_to_year"),
                data: { 'year': year },
                success: function (redata) { $("#id_to_year").html(redata) }
            });
        });

        $("#id_from_month").change(function () {
            var year = $("#id_from_year").val();
            var month = $("#id_from_month").val();
            var url = $("#date_ajax").attr("load_from_day");
            // $("#test").html('ok');
            $.ajax({
                url: url,
                data: { 'year': year, 'month': month },
                success: function (tasrif) { $("#id_from_day").html(tasrif); }
            });

            $.ajax({
                url: $("#date_ajax").attr("load_to_month"),
                data: { 'from_year': $("#id_from_year").val(), 'to_year': $("#id_to_year").val(), 'from_month': $("#id_from_month").val() },
                success: function (redata) { $("#id_to_month").html(redata); }
            });
        });

        $("#id_to_year").change(function () {
            // $("#test").html('ok');
            $.ajax({
                url: $("#date_ajax").attr("load_to_month"),
                data: { 'from_year': $("#id_from_year").val(), 'to_year': $("#id_to_year").val(), 'from_month': $("#id_from_month").val() },
                success: function (redata) { $("#id_to_month").html(redata); }
            });
        });

        $("#id_to_month").change(function () {
            $.ajax({
                url: $("#date_ajax").attr("load_to_day"),
                data: {
                    'from_year': $("#id_from_year").val(),
                    'from_month': $("#id_from_month").val(),
                    'from_day': $("#id_from_day").val(),
                    'to_year': $("#id_to_year").val(),
                    'to_month': $("#id_to_month").val(),
                    "space_type": $(this).attr("")
                },
                success: function (redata) { $("#id_to_day").html(redata); }
            });
        });

        $("#id_from_day").change(function () {
            $.ajax({
                url: $("#date_ajax").attr("load_to_day"),
                data: {
                    'from_year': $("#id_from_year").val(),
                    'from_month': $("#id_from_month").val(),
                    'from_day': $("#id_from_day").val(),
                    'to_year': $("#id_to_year").val(),
                    'to_month': $("#id_to_month").val(),
                },
                success: function (redata) { $("#id_to_day").html(redata); }
            });
        });
    </script>

<script id="load_city_ajax" load_city="/search/ajax/load_city/" load_residence="/search/ajax/load_city_residence/">
    $("#id_country").change(function () {
        $.ajax({
            url: $("#load_city_ajax").attr("load_city"),
            data: { 'country': $("#id_country").val() },
            success: function (redata) {
                $("#id_city").html(redata);
                $.ajax({
                    url: $("#load_city_ajax").attr("load_residence"),
                    data: { 'city': $("#id_city").val() },
                    success: function (redata) { $("#id_residence").html(redata); }
                });
            }
        });
    });
    $("#id_city").change(function () {
        // $("#test").html("load_residence");
        $.ajax({
            url: $("#load_city_ajax").attr("load_residence"),
            data: { 'city': $("#id_city").val() },
            success: function (redata) { $("#id_residence").html(redata); }
        });
    });
</script>

<script id="bookyee_space" book_url="/search/ajax/book/">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $(".book").click(function () {
        $.ajax({
            url: "/residence/book/",
            type: "POST",
            data: {
                "from_year": $("#id_from_year").val(),
                "from_month": $("#id_from_month").val(),
                "from_day": $("#id_from_day").val(),
                "to_year": $("#id_to_year").val(),
                "to_month": $("#id_to_month").val(),
                "to_day": $("#id_to_day").val(),
                "space_type": $(this).attr("space_type"),
                "n_space": $("#id_space_n").val()
            },
            success: function (response) {
                alert(response);
                $(".book").hide();
            }
        });
    });
</script>

{% endblock content_2 %}