DjangoAdmin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import PermissionDenied, LoginRequired

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('accounts.urls')),
    path('residence/', include('residence.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('guide/', include('guide.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('search.urls')),
    path('permission_denied/', PermissionDenied.as_view(),
         name='permission denied'),
    path('login_required/', LoginRequired.as_view()),

]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include

urlpatterns = [
    path('', views.blog, name='blog'),
    # path('', views.new_post.as_view(), name='newpost'),
    path('newpost/', views.new_post, name='newpost'),
    # url(r'^newpost(?P<pk>[0-9]+)/$', views.new_post, name='newpost'),
    path('bloglist/', views.PostList, name='bloglist'),
    # path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    # path('<int:id>/', views.PostDetail, name='post_detail'),
    # path()
    
    url(r'^bloglist/(?P<pk>[0-9]+)/$',
        views.PostDetail.as_view(), name='post_detail'),
    url(r'^bloglist/(?P<postid>\d+)/preference/(?P<userpreference>\d+)/$',
        views.PostPreference, name='postpreference'),
    # url(r'^like/(?P<pk>[0-9]+)/$', views.like_post, name='like_post'),
    # path('like/', views.like_post, name='like_post'),
    url(r'^blogist/(?P<pk>[0-9]+)/edit/$',
        views.UpdatePost.as_view(), name='post_edit'),
    url(r'^bloglist/(?P<pk>[0-9]+)/remove/$',
        views.DeletePost.as_view(), name='post_remove'),



    url(r'^bloglist/(?P<pk>[0-9]+)/approve/$',
        views.comment_approve, name='comment_approve'),
    url(r'^bloglist/(?P<pk>[0-9]+)/remove/$',
        views.comment_remove, name='comment_remove'),

    url(r'^bloglist/(?P<pk>[0-9]+)/comment/$',
        views.addComment, name='addcomment'),


]

residence/urls.py
from homepage.base import *
from . import views

urlpatterns = [
    # path('login/', login, name='login')
    path('my_residence/', views.MyResidence.as_view(), name='my residence'),
    path('add_residence/', views.AddResidence.as_view(), name='add residence'),
    path('<int:id>/', views.ResidenceDetail.as_view(), name='residence detail'),
    path('<int:id>/update/', views.UpdateResidence.as_view(),
         name='update residence'),
    path('<int:id>/delete/', views.DeleteResidence.as_view(),
         name='delete residence'),
    path('<int:id>/space/', views.ShowResidenceSpace.as_view(), name='show space'),
    path('<int:id>/space/add_space/',
         views.AddSpace.as_view(), name='add residence space'),
    path("<int:id>/space_type/", views.ShowSpaceTypes.as_view()),
    path("<int:residence_id>/create_space_type/",
         views.CreateSpaceType.as_view()),
    path("<int:residence_id>/orders/", views.ShowReceivedResidenceOrder.as_view()),
    path('space/<int:space_id>/', views.SpaceDetail.as_view(), name='Space Detail'),
    path('space/<int:space_id>/update/',
         views.UpdateSpace.as_view(), name='Update Space'),
    path('space/<int:space_id>/delete/',
         views.DeleteSpace.as_view(), name='Delete Space'),
    path('space/<int:space_id>/avail/',
         views.CreateSpaceAvailability.as_view(), name='c_s_a'),
    path("space/<int:space_id>/unavail/", views.MakeSpaceUnavailable.as_view()),
    path("space/<int:space_id>/book/", views.BookSpace.as_view()),
    path("space/<int:space_id>/availability/", views.ShowSpaceAvailability.as_view()),
    path("ajax/", include("residence.ajax_handler")),
    path("space_type/<int:space_type_id>/",
         views.ShowSpaceTypeDetail.as_view()),
    path("space_type/<int:space_type_id>/update/",
         views.UpdateSpaceType.as_view()),
    path("space_type/<int:space_type_id>/delete/",
         views.DeleteSpaceType.as_view()),
    path("book/", views.BookSpace.as_view()),
    path("received_order/", views.ShowReceivedResidenceOrder.as_view()),
    path("purchased_order/", views.ShowPurchasedOrder.as_view()),
    path("order/<int:order_id>/", views.ShowSpaceOrderDetail.as_view())
]

residence/models.py
from homepage.base import *
from django.utils.translation import gettext_lazy as _
from .views_1 import is_space_booked, make_space_unavailable, create_avail_space, is_space_available
from homepage.models import UserDetail, City, Country, Address, MyChoice, Cart


#####################################         Models           ########################################################

class Residence(models.Model):
    user_detail = models.ForeignKey(UserDetail, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True, default=None)
    city = models.ForeignKey(
        City, on_delete=models.SET_NULL, null=True, default=None)
    mobile = models.IntegerField(default=None, null=True, blank=True)
    description = models.CharField(
        max_length=255, null=True, blank=True, default=None)
    img = models.ImageField(upload_to='ResidencePhoto',
                            null=True, blank=True, default=None)

    class Meta:
        pass

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)

        if not (exclude and "user_detail" in exclude):
            if Residence.objects.filter(user_detail=self.user_detail, name=self.name).exists():
                if Residence.objects.get(user_detail=self.user_detail, name=self.name).id != self.id:
                    raise ValidationError(
                        "You have already a residence of that name -_-")

    def __str__(self):
        return '%s\'s %s at %s' % (self.user_detail.__str__(), self.name, self.city.__str__())


class SpaceType(models.Model):
    residence = models.ForeignKey(Residence, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    person = models.PositiveIntegerField()
    rent = models.FloatField()
    pic = models.ImageField(upload_to="SpaceTypePhoto",
                            null=True, blank=True, default=None)
    description = models.CharField(
        max_length=255, null=True, blank=True, default=None)

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)

        if exclude and 'residence' in exclude:
            pass
        else:
            if SpaceType.objects.filter(residence=self.residence, name=self.name).exists():
                if SpaceType.objects.get(residence=self.residence, name=self.name).id != self.id:
                    raise ValidationError(
                        "This Residence has alreday a TYPE of the same name -_-")

    def __str__(self):
        return self.name


class Space(models.Model):
    name = models.CharField(max_length=255)
    residence = models.ForeignKey(Residence, on_delete=models.CASCADE)
    space_type = models.ForeignKey(
        SpaceType, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return '%s Space-> %s' % (self.residence.__str__(), self.space_type)

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)

        if exclude and 'residence' in exclude:
            pass
        else:
            if Space.objects.filter(residence=self.residence, name=self.name).exists():
                # print(self.id)
                if Space.objects.get(residence=self.residence, name=self.name).id != self.id:
                    raise ValidationError(
                        "This Residence has already a space of this name")


class SpaceAvailable(models.Model):
    space = models.ForeignKey(Space, on_delete=models.CASCADE)
    avail_from = models.DateField()
    avail_to = models.DateField()

    class Meta:
        ordering = ["space", "avail_from"]

    def __str__(self):
        return '%s from %s to %s' % (self.space.__str__(), str(self.avail_from), str(self.avail_to))

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)


class ResidenceOrder(models.Model):
    guest = models.ForeignKey(UserDetail, on_delete=models.CASCADE)
    space_type = models.ForeignKey(SpaceType, on_delete=models.CASCADE)
    n_space = models.IntegerField()
    book_from = models.DateField()
    book_to = models.DateField()
    booking_time = models.DateTimeField()
    bill = models.FloatField()


class SpaceBooking(models.Model):
    # while saving object of this model firstly the space is made unavailable
    residence_order = models.ForeignKey(
        ResidenceOrder, on_delete=models.CASCADE, related_name="space_booking", null=True)
    space = models.ForeignKey(
        Space, on_delete=models.CASCADE, related_name="space_booking")
    book_from = models.DateField()
    book_to = models.DateField()

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)


def is_space_booked_tricky(space, from_date, to_date):
    return is_space_booked(SpaceBooking, space, from_date, to_date)


# pip install Pillow
# python manage.py makemigrations
# python manage.py sqlmigrate @appname @migrationid
# python manage.py migrate
# django admin username-shoaib password-1234
# python manage.py createsuperuser @username
# python manage.py changepassword @username
# python manage.py createsuperuser -h

residence/forms.py
from .models import Residence, Space, SpaceAvailable, SpaceType
from homepage.base import *
from homepage.models import Country, City
from .views_1 import load_flw_to_day, load_flw_from_day, load_flw_from_month, load_flw_to_month, load_flw_to_year, load_city_choice


class ResidenceForm(forms.ModelForm):

    class Meta:
        model = Residence
        exclude = ['user_detail']
        labels = {"img": "Photo"}

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['country'].queryset = Country.objects.all()
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            country_id = int(self.data.get('country'))
            self.fields['city'].queryset = City.objects.filter(
                country_id=country_id).order_by('city')
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by(
                'city')

        print("ResidenceForm")


class SpaceForm(forms.ModelForm):
    class Meta:
        model = Space
        exclude = ['residence']

    def __init__(self, *args, **kwargs):
        # print("SpaceForm")
        super().__init__(*args, **kwargs)
        residence_id = None
        init_dict = {}
        # form for creating new space
        if kwargs.get('initial', None):
            init_dict = kwargs.get('initial', None)
            if init_dict.get('residence', None):
                residence_id = init_dict.get('residence', None)
        # print("44", self.data)

        if kwargs.get("instance", None):
            instance = kwargs.get("instance", None)
            residence_id = instance.id
            # print(instance, type(instance))
        self.fields['space_type'].queryset = SpaceType.objects.filter(
            residence_id=residence_id)


class SpaceAvailabilityForm(forms.ModelForm):
    class Meta:
        model = SpaceAvailable
        exclude = ['space']


class DateForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        year_choice = [("", "------------")]
        for i in range(datetime.today().year, datetime.today().year+5):
            year_choice += [(i, str(i))]
        self.fields['from_year'] = forms.ChoiceField(
            choices=year_choice, label="From Year")
        self.fields['from_month'] = forms.ChoiceField(
            choices=[("", "------------")], label="From Month")
        self.fields['from_day'] = forms.ChoiceField(
            choices=[("", "------------")], label="From Day")
        self.fields['to_year'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Year')
        self.fields['to_month'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Month')
        self.fields['to_day'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Day')

        if 'from_year' in self.data:
            from_month = int(self.data['from_month'])
            from_year = int(self.data['from_year'])
            from_day = int(self.data['from_day'])
            to_day = int(self.data['to_day'])
            to_month = int(self.data['to_month'])
            to_year = int(self.data['to_year'])

            self.fields['from_month'] = forms.ChoiceField(
                choices=load_flw_from_month(from_year))
            self.fields['from_day'] = forms.ChoiceField(
                choices=load_flw_from_day(from_year, from_month))
            self.fields['to_year'] = forms.ChoiceField(
                choices=load_flw_to_year(from_year))
            self.fields['to_month'] = forms.ChoiceField(
                choices=load_flw_to_month(from_year, to_year, from_month))
            self.fields['to_day'] = forms.ChoiceField(choices=load_flw_to_day(
                from_year, to_year, from_month, to_month, from_day))


class SpaceSearchForm(forms.Form):
    space_n = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 100)], label="Number of Space")
    person_n = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 100)], label="Person per Room")
    max_rent = forms.CharField(label="Maximal Rent", required=False)
    min_rent = forms.CharField(label="Minimal Rent", required=False)
    residence_name = forms.CharField(max_length=255, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        year_choice = [("", "------------")]
        for i in range(datetime.today().year, datetime.today().year+5):
            year_choice += [(i, str(i))]
        self.fields['from_year'] = forms.ChoiceField(
            choices=year_choice, label="From Year")
        self.fields['from_month'] = forms.ChoiceField(
            choices=[("", "------------")], label="From Month")
        self.fields['from_day'] = forms.ChoiceField(
            choices=[("", "------------")], label="From Day")
        self.fields['to_year'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Year')
        self.fields['to_month'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Month')
        self.fields['to_day'] = forms.ChoiceField(
            choices=[("", "------------")], label='To Day')

        if 'from_year' in self.data:
            from_month = int(self.data['from_month'])
            from_year = int(self.data['from_year'])
            from_day = int(self.data['from_day'])
            to_day = int(self.data['to_day'])
            to_month = int(self.data['to_month'])
            to_year = int(self.data['to_year'])

            self.fields['from_month'] = forms.ChoiceField(
                choices=load_flw_from_month(from_year))
            self.fields['from_day'] = forms.ChoiceField(
                choices=load_flw_from_day(from_year, from_month))
            self.fields['to_year'] = forms.ChoiceField(
                choices=load_flw_to_year(from_year))
            self.fields['to_month'] = forms.ChoiceField(
                choices=load_flw_to_month(from_year, to_year, from_month))
            self.fields['to_day'] = forms.ChoiceField(choices=load_flw_to_day(
                from_year, to_year, from_month, to_month, from_day))

        country_choice = [("", "------------")]
        for ob in Country.objects.all():
            country_choice += [(ob.id, str(ob.name))]
        self.fields['country'] = forms.ChoiceField(choices=country_choice)

        self.fields['city'] = forms.ChoiceField(choices=[("", "------------")])

        if 'country' in self.data:
            country = int(self.data.get('country', None))
            self.fields['city'] = forms.ChoiceField(
                choices=load_city_choice(City, country))
        # print('init spacesearch     form')


class CreateSpaceTypeForm(forms.ModelForm):
    
    class Meta:
        model = SpaceType
        exclude = ['residence']
        labels = {"pic": "Photo", "person": "Person per Space"}

residence/templates/add_residence.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content_1 %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content_2 %}

<br> <br>
<div class="container">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            <div class="card searchbox" style="height: max-content;">
                <h3 class="card-header" style="background: #232524; color: #FFFF;">Add Residence</h3>
                <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                <div class="card-body">

                    <form id="form1" method="post" enctype="multipart/form-data" load-city="/search/ajax/load_city/"
                        novalidate>
                        {% csrf_token %}
                        <!-- <table class="form_table"> -->
                        {{ form|crispy }}
                        <!-- </table> -->
                        <br>
                        <div class="text-right">
                            <button type="submit" style="font-family: Ubuntu;" class="btn btn-info btn-lg">Add
                                Residence</button>

                        </div>
                    </form>

                </div>
            </div>

        </div>
        <div class="col-lg-2">

        </div>


    </div>

</div>
<br> <br>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_country").change(function () {

        var url = $("#form1").attr("load-city");
        var country_id = $(this).val();
        // document.getElementById("hi").innerHTML = url;
        $.ajax({
            url: url,
            data: { 'country': country_id },
            success: function (hati) {
                $("#id_city").html(hati);
            }
        });
    });
</script>

{% endblock %}

residence/templates/add_space.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content_1 %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content_2 %}

<br> <br>
<div class="container">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            <div class="card searchbox" style="height: max-content;">
                <h3 class="card-header" style="background: #232524; color: #FFFF;">{{ residence.name }}'s Space</h3>
                <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                <div class="card-body">

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- <table class="form_table"> -->
                        {{ form|crispy }}
                        <!-- </table> -->
                        <br>
                        <div class="text-right">
                            <button type="submit" style="font-family: Ubuntu;" class="btn btn-info btn-lg">Add
                                Space</button>

                        </div>
                    </form>
                    <!-- <a href="/residence/{{ residence.id }}/"><button
                            class="btn btn-outline-dark btn-lg btn-block">{{ residence.name }}</button> </a> -->

                </div>


            </div>

        </div>
        <div class="col-lg-2">

        </div>


    </div>

</div>
<br> <br>

{% endblock %}

residence/templates/book_space.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content_1 %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content_2 %}

<br> <br>
<div class="container">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            <div class="card searchbox" style="height: max-content;">
                <h3 class="card-header" style="background: #232524; color: #FFFF;">Book Space</h3>
                <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                <div class="card-body">

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- <table class="form_table"> -->
                        {{ form|crispy }}
                        <!-- </table> -->
                        <br>
                        <div class="text-right">
                            <button type="submit" value="Book" style="font-family: Ubuntu;"
                                class="btn btn-info btn-lg">Book Space</button>

                        </div>
                    </form>
                    <!-- <a href="/residence/{{ residence.id }}/"><button
                            class="btn btn-outline-dark btn-lg btn-block">{{ residence.name }}</button> </a> -->

                </div>


            </div>

        </div>
        <div class="col-lg-2">

        </div>


    </div>

</div>
<br> <br>


<script id="date_ajax" load_to_year="/residence/ajax/load_to_year/" load_to_month="/residence/ajax/load_to_month/"
    load_to_day="/residence/ajax/load_to_day/" load_from_month="/residence/ajax/load_from_month/"
    load_from_day="/residence/ajax/load_from_day/">

        $("#b1").click(function () { $("#test").show(); });
        $("#b1").dblclick(function () { $("#test").hide(); });


        $("#id_from_year").change(function () {
            // $("#test").html('changed');
            var year = $(this).val();
            var url = $("#date_ajax").attr("load_from_month");
            // $("#test").html(url);

            $.ajax({
                url: url,
                data: { 'year': year },
                success: function (shoaib) { $("#id_from_month").html(shoaib); }
            });

            $.ajax({
                url: $("#date_ajax").attr("load_to_year"),
                data: { 'year': year },
                success: function (redata) { $("#id_to_year").html(redata) }
            });
        });

        $("#id_from_month").change(function () {
            var year = $("#id_from_year").val();
            var month = $("#id_from_month").val();
            var url = $("#date_ajax").attr("load_from_day");
            // $("#test").html('ok');
            $.ajax({
                url: url,
                data: { 'year': year, 'month': month },
                success: function (tasrif) { $("#id_from_day").html(tasrif); }
            });

            $.ajax({
                url: $("#date_ajax").attr("load_to_month"),
                data: { 'from_year': $("#id_from_year").val(), 'to_year': $("#id_to_year").val(), 'from_month': $("#id_from_month").val() },
                success: function (redata) { $("#id_to_month").html(redata); }
            });
        });

        $("#id_to_year").change(function () {
            // $("#test").html('ok');
            $.ajax({
                url: $("#date_ajax").attr("load_to_month"),
                data: { 'from_year': $("#id_from_year").val(), 'to_year': $("#id_to_year").val(), 'from_month': $("#id_from_month").val() },
                success: function (redata) { $("#id_to_month").html(redata); }
            });
        });

        $("#id_to_month").change(function () {
            $.ajax({
                url: $("#date_ajax").attr("load_to_day"),
                data: {
                    'from_year': $("#id_from_year").val(),
                    'from_month': $("#id_from_month").val(),
                    'from_day': $("#id_from_day").val(),
                    'to_year': $("#id_to_year").val(),
                    'to_month': $("#id_to_month").val(),
                },
                success: function (redata) { $("#id_to_day").html(redata); }
            });
        });

        $("#id_from_day").change(function () {
            $.ajax({
                url: $("#date_ajax").attr("load_to_day"),
                data: {
                    'from_year': $("#id_from_year").val(),
                    'from_month': $("#id_from_month").val(),
                    'from_day': $("#id_from_day").val(),
                    'to_year': $("#id_to_year").val(),
                    'to_month': $("#id_to_month").val(),
                },
                success: function (redata) { $("#id_to_day").html(redata); }
            });
        });


    </script>

{% endblock %}

residence/templates/residence_order_detail.html
{% extends 'base.html' %}

{% block content_1 %}
<title></title>
{% endblock content_1 %}

{% block header %}
{% endblock %}

{% block content_2 %}
<div class="bgbg">
    <br> <br>
    <div class="container">
        <div class="row">
            <div class="col-lg-2">

            </div>
            <div class="col-lg-8">
                <div class="card searchbox" style="height: max-content;">
                    <h3 class="card-header" style="background: #232524; color: #FFFF;">Received Residence Orders</h3>
                    <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                    <div class="card-body">
                        <br>
                        <table class="table">
                            <thead>
                                <tr>

                                    <th scope="col">Order ID</th>
                                    <th scope="col">Residence</th>
                                    <th scope="col">Space Type</th>
                                    <th scope="col">No Of Space</th>
                                    <th scope="col">From</th>
                                    <th scope="col">To</th>
                                    <th scope="col">Booked At</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <td>
                                        {{order.id}}
                                        </a>
                                    </td>

                                    <td> <a href="/residence/{{order.space_type.residence.id}}/"
                                            class="btn btn-light">{{order.space_type.residence.name}}</a>
                                    </td>
                                    <td> <a href="/residence/space_type/{{order.space_type.id}}/"
                                            class="btn btn-light">{{order.space_type.name}}</a>
                                    </td>
                                    <td>{{order.n_space}}</td>
                                    <td>{{order.book_from}}</td>
                                    <td>{{order.book_to}}</td>
                                    <td>{{order.booking_time}}</td>


                                <tr>
                                    {% endfor %}

                            </tbody>
                        </table> <br>



                        <br><br>




                    </div>
                </div>

            </div>
            <div class="col-lg-2">

            </div>


        </div>

    </div>
    <br> <br>
</div>
{% endblock %}

residence/templates/show_space_type_detail.html
{% extends 'base.html' %}


{% block content_1 %}
<title>Space Type Detail</title>
{% endblock content_1 %}

{% block header %}
{{space_type.name}}
{% endblock %}

{% block content_2 %}


<table class="body_table">
    <tr>
        <td colspan="2">
            {%if space_type.pic %}
            <img src="{{space_type.pic.url}}" class="image_ste">
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>$ {{space_type.rent}} per day</td>
    </tr>
    <tr>
        <td>For {{space_type.person}} Person</td>
    </tr>
    <tr>
        <td>{{space_type.description}}</td>
    </tr>
</table>


{% endblock content_2 %}

{% block body_op %}
<a href="/residence/{{space_type.residence.id}}/"><button
        class="body_op_button_class">{{space_type.residence.name}}</button></a>
{% if space_type.residence.user_detail.user == request.user %}
<a href="update/"><button class="body_op_button_class">Update</button></a>
<a href="delete/"><button class="body_op_button_class">Delete</button></a>
{% endif %}
{% endblock %}

residence/templates/update_residence.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content_1 %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content_2 %}

<br> <br>
<div class="container">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            <div class="card searchbox" style="height: max-content;">
                <h3 class="card-header" style="background: #232524; color: #FFFF;">{{ residence.name }}</h3>
                <!-- <img src="user.jpg" style="align-self: center;" class="card-img img-thumbnail" alt="..."> -->
                <div class="card-body">

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- <table class="form_table"> -->
                        {{ form|crispy }}
                        <!-- </table> -->
                        <br>
                        <div class="text-right">
                            <button type="submit" style="font-family: Ubuntu;"
                                class="btn btn-info btn-lg">Update</button>

                        </div>
                    </form>
                    <!-- <a href="/residence/{{ residence.id }}/"><button
                            class="btn btn-outline-dark btn-lg btn-block">{{ residence.name }}</button> </a> -->

                </div>


            </div>

        </div>
        <div class="col-lg-2">

        </div>


    </div>

</div>
<br> <br>

<script id="load_city_ajax" load_city="/search/ajax/load_city/" load_residence="/search/ajax/load_city_residence/">
    $("#id_country").change(function () {
        $.ajax({
            url: $("#load_city_ajax").attr("load_city"),
            data: { 'country': $("#id_country").val() },
            success: function (redata) {
                $("#id_city").html(redata);
                $.ajax({
                    url: $("#load_city_ajax").attr("load_residence"),
                    data: { 'city': $("#id_city").val() },
                    success: function (redata) { $("#id_residence").html(redata); }
                });
            }
        });
    });
    $("#id_city").change(function () {
        // $("#test").html("load_residence");
        $.ajax({
            url: $("#load_city_ajax").attr("load_residence"),
            data: { 'city': $("#id_city").val() },
            success: function (redata) { $("#id_residence").html(redata); }
        });
    });
</script>


{% endblock %}